# Lab 1: Introduction to Financial Python
## Xamir Rojas 


# 01 Python: Data Types and Data Structures

## Strings

In [1]:
my_string1 = 'Welcome to'
my_string2 = "QuantConnect"
print(my_string1 + ' ' + my_string2)

Welcome to QuantConnect


In [2]:
# Xamir
my_string1 = 'Hello World! I am '
my_string2 = "Xamir Rojas"
print(my_string1 + ' ' + my_string2)

Hello World! I am  Xamir Rojas


## Ints

In [3]:
my_int = 10
print(my_int)
print(type(my_int))

10
<class 'int'>


In [4]:
# Xamir
xamir_int = 3
print(xamir_int)
print(type(xamir_int))

3
<class 'int'>


## Strings to Int, String to Float

In [5]:
my_string = "100"
print(type(my_string))
my_int = int(my_string)
print(type(my_int))

<class 'str'>
<class 'int'>


In [6]:
# Xamir
xamir_string = "333"
print(type(xamir_string))
xamir_int = int(xamir_string)
print(type(xamir_int))

<class 'str'>
<class 'int'>


In [7]:
my_string = "100"
my_float = float(my_string)
print(type(my_float))

<class 'float'>


In [8]:
# Xamir
xamir_string = "333"
xamir_float = float(xamir_string)
print(type(xamir_float))
print(xamir_float)

<class 'float'>
333.0


## Bools

In [9]:
my_bool = False
print(my_bool)
print(type(my_bool))

False
<class 'bool'>


In [10]:
# Xamir
isStudent = True
print(isStudent)
print(type(isStudent))

True
<class 'bool'>


## Operations

In [11]:
print("Addition ", 1+1)
print("Subtraction ", 5-2)
print("Multiplication ", 2*3)
print("Division ", 10/2)
print('exponent', 2**3)

Addition  2
Subtraction  3
Multiplication  6
Division  5.0
exponent 8


In [12]:
# Xamir
print("Xamir Addition ", 3+3)
print("Xamir Subtraction ", 3-5)
print("Xamir Multiplication ", -1*3)
print("Xamir Division ", 13/3)
print('Xamir exponent', 2**8)

Xamir Addition  6
Xamir Subtraction  -2
Xamir Multiplication  -3
Xamir Division  4.333333333333333
Xamir exponent 256


In [13]:
print(1/3)
print(1.0/3)

0.3333333333333333
0.3333333333333333


In [14]:
# Xamir 
print(3/3)
print(3.0/3)
print(33/7)
print(33.0/7)

1.0
1.0
4.714285714285714
4.714285714285714


## Lists

In [15]:
my_list = ['Quant', 'Connect', 1,2,3]
print(my_list)

['Quant', 'Connect', 1, 2, 3]


In [16]:
# Xamir
xamir_list = ['Xamir', 'Rojas', 3.0, 3 , True, ["sub_list"]]
print(xamir_list)

['Xamir', 'Rojas', 3.0, 3, True, ['sub_list']]


In [17]:
my_list = ['Quant', 'Connect', 1,2,3]
print(len(my_list))
print(my_list[0])
print(my_list[len(my_list) -1])

5
Quant
3


In [18]:
# Xamir
xamir_list = ['Xamir', 'Rojas', 3.0, 3 , True, ["sub_list"]]
print("Number of items in Xamir's List :"+ str(len(xamir_list)))
print("First Item in Xamir's List" + str(xamir_list[0]))
print("Last item in the list" +str(xamir_list[len(xamir_list) -1]))

Number of items in Xamir's List :6
First Item in Xamir's ListXamir
Last item in the list['sub_list']


In [19]:
my_list = ['Quant','Connect',1,2,3]
my_list[2] = 'go'
print(my_list)

['Quant', 'Connect', 'go', 2, 3]


In [20]:
# Xamir
xamir_list = ['Xamir', 'Rojas', 3.0, 3 , True, ["sub_list"]]
xamir_list[2] = 'G'
print(xamir_list)

['Xamir', 'Rojas', 'G', 3, True, ['sub_list']]


In [21]:
my_list = ['Quant']
my_list.append('Connect')
print(my_list)
my_list.remove('Quant')
print(my_list)

['Quant', 'Connect']
['Connect']


In [22]:
# Xamir
xamir_list = ['X','A']
xamir_list.append('M')
print(xamir_list)
xamir_list.remove('A')
print(xamir_list)

['X', 'A', 'M']
['X', 'M']


### Lists slicing
https://numpy.org/doc/stable/reference/arrays.indexing.html#basic-slicing-and-indexing

In [23]:
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:3])

['Connect', 1]


In [24]:
# Xamir
xamir_list = ['Xamir', 'Rojas', 3.0, 3 , True, ["sub_list"]]
print(xamir_list[1:3])

['Rojas', 3.0]


In [25]:
print(my_list[1:])

['Connect', 1, 2, 3]


In [26]:
# Xamir
print(xamir_list[1:])

['Rojas', 3.0, 3, True, ['sub_list']]


In [27]:
print(my_list[:3])

['Quant', 'Connect', 1]


In [28]:
# Xamir
print(xamir_list)
print(xamir_list[:3])
print(xamir_list[1::2]) # Starting at 1 "jumpling" 2 positions
print(xamir_list[0::2]) # Starting at 0 "jumpling" 2 positions
print(xamir_list[0::3])# Starting at 0 "jumpling" 3 positions

['Xamir', 'Rojas', 3.0, 3, True, ['sub_list']]
['Xamir', 'Rojas', 3.0]
['Rojas', 3, ['sub_list']]
['Xamir', 3.0, True]
['Xamir', 3]


In [29]:
my_tuple = ('Welcome','to','QuantConnect')

In [30]:
# Xamir
xamir_tuple = ('This is', "Xamir's" , 'tuple')
print(xamir_tuple)

('This is', "Xamir's", 'tuple')


In [31]:
my_tuple = ('Welcome','to','QuantConnect')
print(my_tuple[1:])

('to', 'QuantConnect')


In [32]:
# tuples are consts. cant be modified
xamir_tuple = ('This is', "Xamir's" , 'tuple','tuple')
print(xamir_tuple[1:])

("Xamir's", 'tuple', 'tuple')


In [33]:
stock_list = ['AAPL','GOOG','IBM','AAPL','IBM','FB','F','GOOG']
stock_set = set(stock_list)
print(stock_set)

{'AAPL', 'FB', 'GOOG', 'F', 'IBM'}


In [34]:
# sets doesnt repeat items
xamir_stock_list = ['TSLA','GOOG','TSLA','AAPL','TSLA','TSLA','F','GOOG']
xamir_stock_set = set(xamir_stock_list)
print(xamir_stock_set)

{'GOOG', 'TSLA', 'F', 'AAPL'}


In [35]:
my_dic = {'AAPL':'AAPLE', 'FB':'FaceBook', 'GOOG':'Alphabet'}

In [36]:
# Xamir
xamir_dic = {'name':'xamir','subjects':[{'name':'AlG'},{'name':'MET'}]}
print(xamir_dic)
print(type(xamir_dic))

{'name': 'xamir', 'subjects': [{'name': 'AlG'}, {'name': 'MET'}]}
<class 'dict'>


In [37]:
print(my_dic['GOOG'])

Alphabet


In [38]:
# Xamir
xamir_dic['subjects'][0]

{'name': 'AlG'}

In [39]:
my_dic['GOOG'] = 'Alphabet Company'
print(my_dic['GOOG'])

Alphabet Company


In [40]:
# Xamir
xamir_dic['subjects'][0] = 'ALGO'
print(xamir_dic['subjects'][0])

ALGO


In [41]:
print(my_dic.keys())

dict_keys(['AAPL', 'FB', 'GOOG'])


In [42]:
# Xamir
print(xamir_dic.keys())
xamir_list_of_keys = xamir_dic.keys()
print(xamir_list_of_keys)

dict_keys(['name', 'subjects'])
dict_keys(['name', 'subjects'])


In [43]:
my_str = 'Welcome to QuantConnect'
print(my_str[8:])

to QuantConnect


In [44]:
# Xamir
xamir_str = 'Xamir Rojas '
print(xamir_str[8:])

jas 


In [45]:
print('Counting the number of e appears in this sentence'.count('e'))
print('The first time e appears in this sentence'.find('e'))
print('all the a in this sentence now becomes e'.replace('a','e'))

7
2
ell the e in this sentence now becomes e


In [46]:
# Xamir
print('In the next string x appears (times):' +str('Counting the number of x appears in this sentence: xamir'.count('x')))
print('The first time f appears in this sentence fff'.find('f'))
print('The first time f appears in this sentence fff'[:5])
print('all the s in this sentence now becomes z'.replace('s','z'))

In the next string x appears (times):2
4
The f
all the z in thiz zentence now becomez z


In [47]:
Time = '2016-04-01 09:43:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)
hour = time.split(':')[0]
print(hour)

2016-04-01 09:43:00
09


In [48]:
# Xamir
xamir_Time = '2021-10-16 20:08:00'
xamir_splited_list = xamir_Time.split(' ')
xamir_date = xamir_splited_list[0]
xamir_time = xamir_splited_list[1]
print(xamir_date, xamir_time)
xamir_hour = xamir_time.split(':')[0]
print(xamir_hour)

2021-10-16 20:08:00
20


In [49]:
my_time = 'Hour: {}, Minute:{}'.format('09','43')
print(my_time)

Hour: 09, Minute:43


In [50]:
# Xamir
xamir_time = 'Hour: {}, Minute:{}'.format('20','10')
print(xamir_time)

Hour: 20, Minute:10


In [51]:
print('the pi number is %f'%3.14)
print('%s to %s'%('Welcome','Quantconnect'))

the pi number is 3.140000
Welcome to Quantconnect


In [52]:
# Xamir
print('the e number is %f'% 2.72)
print('%s to %s'%('Xamir','Rojas'))

the e number is 2.720000
Xamir to Rojas


# 02 Python: Logical Operations and Loops
[Tutorials / Introduction to Financial Python/ Logical Operations and Loops](https://www.quantconnect.com/tutorials/introduction-to-financial-python/logical-operations-and-loops)


In [53]:
print(1 == 0)
print(1 == 1)
print(1 != 0)
print(5 >= 5)
print(5 >= 6)

False
True
True
True
False


In [54]:
# Xamir
print(1 == "1")
print([]==[])
print({}=={})
print(True == 1)
print({'name':'Xamir'}=={'name':'Xamir'})
print({'name':'Xamir'}!={'name':'xamir'})
print('xamir'>='xam')
print('xamir'>='xamir rojas')


False
True
True
True
True
True
True
False


In [55]:
print(2 > 1 and 3 > 2)
print(2 > 1 and 3 < 2) 
print(2 > 1 or 3 < 2)
print(2 < 1 and 3 < 2)

True
False
True
False


In [56]:
# Xamir
print("2" > "1" and "3" > "2")
print(100 > 1 and 300 < 2) 
print(True < 1 or False < 2)
print(2 < 1 and 3 < 2)

True
False
True
False


In [57]:
print((3 > 2 or 1 < 3) and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))
print(3 > 2 or 1 < 3 and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))

False
True


In [58]:
# Xamir
print(5<10<100)
isFalse = ("3" > "2" or 1 < 3) and ("1"!=1 and "XAMIR" > "xamir" ) and not ( 1 < 5 < 10 or 4 < 3 and (1!=3 and 4>3))
print(isFalse)
print(not isFalse)
print("a" is "a" and "a" is True)


True
False
True
False




```python
if statement1:
    # if the statement1 is true, execute the code here.
    # code.....
    # code.....
elif statement2:
    # if the statement 1 is false, skip the codes above to this part.
    # code......
    # code......
else:
    # if none of the above statements is True, skip to this part
    # code......
```



In [59]:
i = 0
if i == 0:
    print('i==0 is True')

i==0 is True


In [60]:
# Xamir
a = True
b = 1
if a == b:
  print('{} == {}'.format(a,b))

True == 1


In [61]:
p = 1 > 0
q = 2 > 3
if p and q:
    print('p and q is true')
elif p and not q:
    print('q is false')
elif q and not p:
    print('p is false')
else:
    print('None of p and q is true')

q is false


In [62]:
# Xamir
x = 'xamir'
r = ''
if x and not r:
  print(" '{}' and not '{}' is True!".format(x,r))
elif x and r:
  print(" '{}' and  '{}' is False!".format(x,r))
elif x and not x:
  print(" '{}' and  not '{}' is False!".format(x,x))
else:
  print("x is '{}' and r is '{}!".format(x,r))


 'xamir' and not '' is True!


In [63]:
i = 0
while i < 5:
    print(i)
    i += 1 

0
1
2
3
4


In [64]:
# Xamir
i = 0
while True:
  i+=1
  print(i)
  if i==8:
    break

1
2
3
4
5
6
7
8


In [65]:
for i in [1,2,3,4,5]:
    print(i)

1
2
3
4
5


In [66]:
# Xamir
for i in 'xamir':
  print(i)

x
a
m
i
r


In [67]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = []
for i in stocks:
    if i not in selected:
        new_list.append(i)
print(stocks)

['AAPL', 'GOOG', 'IBM', 'FB', 'F', 'V', 'G', 'GE']


In [68]:
# Xamir 
users = [{'name':'xamir'},{'name':'user 2'},{'name':' user 3'}]
premium_users = [{'name':'xamir'}]
non_premium_users = []
for i in users:
  if i not in premium_users:
    non_premium_users.append(i)
print(" Non premium users " + str(non_premium_users))

 Non premium users [{'name': 'user 2'}, {'name': ' user 3'}]


In [69]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for i in stocks:
    print (i)
    if i == 'FB':
        break

AAPL
GOOG
IBM
FB


In [70]:
# Xamir
users = [{'name':'xamir'},{'name':'user 2'},{'name':' user 3'}]
for i in users:
  print(i['name'])
  if(i['name'] == 'user 2'):
    break

xamir
user 2


In [71]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for i in stocks:
    if i == 'FB':
        continue
    print(i)

AAPL
GOOG
IBM
F
V
G
GE


In [72]:
# Xamir
users = [{'name':'xamir'},{'name':'user 2'},{'name':' user 3'}]
for i in users:
  if i['name'] == 'user 2':
    print('I have found {}'.format(i['name']))
    continue
  print(i)

{'name': 'xamir'}
I have found user 2
{'name': ' user 3'}


## List Comprehension

In [73]:
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**2)
print(squares)

[1, 4, 9, 16, 25]


In [74]:
# Xamir
base = [1,2,3,4,5]
results = []
for i in base:
  results.append(i**5)
print(results)

[1, 32, 243, 1024, 3125]


In [75]:
list_example = [1,2,3,4,5]
squares = [x**2 for x in list_example]
print(squares)

[1, 4, 9, 16, 25]


In [76]:
# Xamir
results = [x**10 for x in [5,6,7,8,9]]
print(results)

[9765625, 60466176, 282475249, 1073741824, 3486784401]


In [77]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = [x for x in stocks if x in selected]
print(new_list)

['AAPL', 'IBM']


In [78]:
# Xamir
users = [{'name':'xamir'},{'name':'user 2'},{'name':' user 3'}]
premium_users = [{'name':'xamir'}]
non_premium_users = [x for x in users if x not in premium_users]
print(non_premium_users)

[{'name': 'user 2'}, {'name': ' user 3'}]


In [79]:
print([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print([str(x)+' vs '+str(y) for x in ['AAPL','GOOG','IBM','FB'] for y in ['F','V','G','GE'] if x!=y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['AAPL vs F', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs F', 'GOOG vs V', 'GOOG vs G', 'GOOG vs GE', 'IBM vs F', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'FB vs F', 'FB vs V', 'FB vs G', 'FB vs GE']


In [80]:
# Xamir
print([(x, y) for x in [2,4,6] for y in [1,3,5]])
print([x['name']+' vs '+ y['name'] for x in [{'name':'xamir'},{'name':'user 2'},{'name':' user 3'}] for y in [{'name':'xamir'},{'name':'user 2'},{'name':' user 3'}] if x!=y])


[(2, 1), (2, 3), (2, 5), (4, 1), (4, 3), (4, 5), (6, 1), (6, 3), (6, 5)]
['xamir vs user 2', 'xamir vs  user 3', 'user 2 vs xamir', 'user 2 vs  user 3', ' user 3 vs xamir', ' user 3 vs user 2']


# 03 Python:Functions and Objective-Oriented Programming
[Tutorials /  Introduction to Financial Python  /  Functions and Objective-Oriented Programming](https://www.quantconnect.com/tutorials/introduction-to-financial-python/functions-and-objective-oriented-programming)

In [81]:
def product(x,y):
    return x*y
print(product(2,3))
print(product(5,10))

6
50


In [82]:
# Xamir
def multiply_the_numbers (*args):
  total = 1
  for num in args:
    total *= num
  return total
print(multiply_the_numbers(2,3,4))
print(multiply_the_numbers(2,3,4,5,6,7,8,9,10,11,12))

24
479001600


In [83]:
def say_hi():
    print('Welcome to QuantConnect')
say_hi()

Welcome to QuantConnect


In [84]:
# Xamir
def say_something():
  print('Something')
say_something()

Something


In [85]:
print(range(10))
print(range(1,11))
print(range(1,11,2))

range(0, 10)
range(1, 11)
range(1, 11, 2)


In [86]:
# Xamir
print(range(100))
print(range(-30,30))
print(range(-100,100,5))

range(0, 100)
range(-30, 30)
range(-100, 100, 5)


In [87]:
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print('The length of tickers is {}'.format(len(tickers)))
for i in range(len(tickers)):
    print(tickers[i])

The length of tickers is 8
AAPL
GOOG
IBM
FB
F
V
G
GE


In [88]:
# Xamir
food = ['hamburguer','apple','banana']
print('The length of  is {}'.format(len(food)))
for i in range(len(food)):
    print(food[i])

The length of  is 3
hamburguer
apple
banana


**map(fun, iter)**
function returns a map object(which is an iterator) of the results after applying the given function to each item of a given iterable (list, tuple etc.)
Parameters :
* fun : It is a function to which map passes each element of given iterable.
* iter : It is a iterable which is to be mapped.


```python
# Python program to demonstrate working
# of map.

# Return double of n
def addition(n):
	return n + n

# We double all numbers using map()
numbers = (1, 2, 3, 4)
result = map(addition, numbers)
print(list(result))
#[2, 4, 6, 8]
```



In [89]:
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print(list(map(len,tickers)))

[4, 4, 3, 2, 1, 1, 1, 2]


In [90]:
# Xamir
def double(food_name):
  return food_name + food_name
food = ['hamburguer','apple','banana']
print(list(map(double,food)))


['hamburguerhamburguer', 'appleapple', 'bananabanana']


The lambda operator(lambda arguments : expression)is a way to create small anonymous functions. These functions are just needed where they have been created. For example:

In [91]:
list(map(lambda x: x**2, range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [92]:
# Xamir
list(map(lambda x:x+x,food))


['hamburguerhamburguer', 'appleapple', 'bananabanana']

In [93]:
list(map(lambda x, y: x+y, [1,2,3,4,5],[5,4,3,2,1]))

[6, 6, 6, 6, 6]

In [94]:
# Xamir
list(map(lambda x,y:x+y,"Hamburger","Banana"))

['HB', 'aa', 'mn', 'ba', 'un', 'ra']

In [95]:
sorted([5,2,3,4,1])

[1, 2, 3, 4, 5]

In [96]:
# Xamir
sorted([1000.-50,0,29,True])

[0, True, 29, 950.0]

In [97]:
price_list = [('AAPL',144.09),('GOOG',911.71),('MSFT',69),('FB',150),('WMT',75.32)]
sorted(price_list, key = lambda x: x[1])

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOG', 911.71)]

In [98]:
# Xamir
users = [{'name':' user 1', 'age':'22'},{'name':' user 2' ,'age':'19'},{'name':' user 3' ,'age':'25'},{'name':' user 4' ,'age':'40'}]
sorted(users, key = lambda x: x['age'])

[{'age': '19', 'name': ' user 2'},
 {'age': '22', 'name': ' user 1'},
 {'age': '25', 'name': ' user 3'},
 {'age': '40', 'name': ' user 4'}]

In [99]:
price_list = [('AAPL',144.09),('GOOG',911.71),('MSFT',69),('FB',150),('WMT',75.32)]
sorted(price_list, key = lambda x: x[1],reverse = True)

[('GOOG', 911.71), ('FB', 150), ('AAPL', 144.09), ('WMT', 75.32), ('MSFT', 69)]

In [100]:
# Xamir
users = [{'name':' user 1', 'age':'22'},{'name':' user 2' ,'age':'19'},{'name':' user 3' ,'age':'25'},{'name':' user 4' ,'age':'40'}]
sorted(users, key = lambda x: x['age'], reverse=True)


[{'age': '40', 'name': ' user 4'},
 {'age': '25', 'name': ' user 3'},
 {'age': '22', 'name': ' user 1'},
 {'age': '19', 'name': ' user 2'}]

In [101]:
price_list = [('AAPL',144.09),('GOOG',911.71),('MSFT',69),('FB',150),('WMT',75.32)]
price_list.sort(key = lambda x: x[1])
print(price_list)

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOG', 911.71)]


In [102]:
users = [{'name':'user 1', 'age':'22'},{'name':' user 2' ,'age':'19'},{'name':' user 3' ,'age':'25'},{'name':' user 4' ,'age':'40'}]
users.sort(key = lambda x: x['age'])
print(users)

[{'name': ' user 2', 'age': '19'}, {'name': 'user 1', 'age': '22'}, {'name': ' user 3', 'age': '25'}, {'name': ' user 4', 'age': '40'}]


In [103]:
class stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1
 
    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1
 
    def print_return(self):
        print(self.rate_return)

In [104]:
# Xamir
class user:
    def __init__(self,name,age):
      self.name = name
      self.age = age
    def get_older(self,age):
      self.age = age
    def __str__(self):
      return('User name: {}, age: {}'.format(self.name,self.age))


xamir = user('xamir',22)
print(xamir)

User name: xamir, age: 22


In [105]:
apple = stock('AAPL', 143.69, 144.09, 20109375)
google = stock('GOOG', 898.7, 911.7, 1561616)

In [106]:
# Xamir
user2 = user('user 2',30)
user3 = user('user 3',5)

In [107]:
apple.ticker
google.print_return()
google.update(912.8,913.4)
google.print_return()

0.014465338822744034
0.0006573181419806673


In [108]:
# Xamir
print(user2.name)
user2.get_older(100)
print(user2)

user 2
User name: user 2, age: 100


In [109]:
apple.ceo = 'Tim Cook'
apple.ceo

'Tim Cook'

In [110]:
# Xamir
user2.name = 'New user 2'
user2.name

'New user 2'

In [111]:
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'ceo',
 'close',
 'open',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'volume']

In [112]:
# Xamir
dir(user2)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'age',
 'get_older',
 'name']

In [113]:
class child(stock):
    def __init__(self,name):
        self.name = name

In [114]:
# Xamir
class user_child(user):
    def __init__(self,name):
        self.name = name
    def new_method(self):
        print('new method!!')

In [115]:
aa = child('aa')
print(aa.name)
aa.update(100,102)
print(aa.open)
print(aa.close)
print(aa.print_return())

aa
100
102
0.020000000000000018
None


In [116]:
# Xamir
user2_child = user_child('uwu')

print(user2_child.name)
user2_child.get_older(333)
print(user2_child.age)
print(user2_child)
user2_child.new_method()

uwu
333
User name: uwu, age: 333
new method!!


# 04 Python: NumPy and Basic Pandas
[Tutorials /  Introduction to Financial Python  /  NumPy and Basic Pandas](https://www.quantconnect.com/tutorials/introduction-to-financial-python/numpy-and-basic-pandas)

In [117]:
import numpy as np

In [118]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


In [119]:
# Xamir
"""
Array of values of the same type
ndarray = n dimensional array
"""
xamir_population_list = [300,200,900,700,-55.3,452.2,321,456,789,300]
xamir_population_array = np.array(xamir_population_list)
print(xamir_population_array,type(xamir_population_array))


[300.  200.  900.  700.  -55.3 452.2 321.  456.  789.  300. ] <class 'numpy.ndarray'>


In [120]:
Ar = np.array([[1,3],[2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


In [121]:
# Xamir
"""
Multi-dimensional array
shape: tuple of ints
The elements of the shape tuple give the lengths of the corresponding array dimensions.
"""
xamir_matrix = np.array([
                         [[1,2,3],[4,5,6]],
                         [[7,8,9],[10,11,12]]
                         ])
print(xamir_matrix,type(xamir_matrix))


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] <class 'numpy.ndarray'>


In [122]:
print(Ar.shape)

(2, 2)


In [123]:
# Xamir
"""
shape: tuple of ints
The elements of the shape tuple give the lengths of the corresponding array dimensions.
"""
print(xamir_matrix.shape)

(2, 2, 3)


In [124]:
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


In [125]:
# Xamir
print(xamir_matrix[0])
print(xamir_matrix[0][0])
print(xamir_matrix[0][0][0])

[[1 2 3]
 [4 5 6]]
[1 2 3]
1


In [126]:
print('the first column: ', Ar[:,0])
print('the second column: ', Ar[:,1])

the first column:  [1 2]
the second column:  [3 4]


In [127]:
# Xamir
"""
[:] all elements
"""
# in all rows choose first element (first column)
print('the first column: ', xamir_matrix[:,0]) 
# in all rows choose second element (second column)
print('the second column: ', xamir_matrix[:,1])
# in all rows, in all columns choose first element 
print('the second column: ', xamir_matrix[:,:,0])



the first column:  [[1 2 3]
 [7 8 9]]
the second column:  [[ 4  5  6]
 [10 11 12]]
the second column:  [[ 1  4]
 [ 7 10]]


In [128]:
print(np.log(price_array))

[4.96793654 4.98244156 4.9675886  4.96995218 4.96633504 4.96018375]


In [129]:
# Xamir
"""
Array functions 
"""
print(np.log(xamir_matrix))


[[[0.         0.69314718 1.09861229]
  [1.38629436 1.60943791 1.79175947]]

 [[1.94591015 2.07944154 2.19722458]
  [2.30258509 2.39789527 2.48490665]]]


In [130]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

143.89666666666668
0.9673790478515796
863.38
145.83


In [131]:
# Xamir
print(np.mean(xamir_matrix))
print(np.std(xamir_matrix))
print(np.sum(xamir_matrix))
print(np.max(xamir_matrix))

6.5
3.452052529534663
78
12


In [132]:
import pandas as pd

In [133]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
s

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64

In [134]:
# Xamir
"""
indexing column 
"""
sr = pd.Series([33.3,77.7,224,100,10])
print(sr)
print(sr.values)
print(sr.index)
print(sr.shape)
sr[[0,4,2]]

0     33.3
1     77.7
2    224.0
3    100.0
4     10.0
dtype: float64
[ 33.3  77.7 224.  100.   10. ]
RangeIndex(start=0, stop=5, step=1)
(5,)


0     33.3
4     10.0
2    224.0
dtype: float64

In [135]:
s = pd.Series(price,index = ['a','b','c','d','e','f'])
s

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64

In [136]:
# Xamir
xamir_serie = pd.Series([33.3,77.7,224,100,10],index = ["val 1","val 2","val 3","val 4","val 5"])
xamir_serie

val 1     33.3
val 2     77.7
val 3    224.0
val 4    100.0
val 5     10.0
dtype: float64

In [137]:
s.index = [6,5,4,3,2,1]
s

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64

In [138]:
# Xamir
xamir_serie.index = [1,2,3,4,5]
xamir_serie

1     33.3
2     77.7
3    224.0
4    100.0
5     10.0
dtype: float64

In [139]:
print(s[1:])
print(s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


In [140]:
# Xamir
print(xamir_serie[:])
print(xamir_serie[2:3])
print(xamir_serie[:3])
print(xamir_serie[0:])

1     33.3
2     77.7
3    224.0
4    100.0
5     10.0
dtype: float64
3    224.0
dtype: float64
1     33.3
2     77.7
3    224.0
dtype: float64
1     33.3
2     77.7
3    224.0
4    100.0
5     10.0
dtype: float64


In [141]:
print(s[4])
s[4] = 0
print(s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


In [142]:
# Xamir
xamir_serie[1] = 777
xamir_serie

1    777.0
2     77.7
3    224.0
4    100.0
5     10.0
dtype: float64

In [143]:
s = pd.Series(price, name = 'Apple Price List')
print(s)
print(s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Price List, dtype: float64
Apple Price List


In [144]:
# Xamir
xamir_serie = pd.Series([33.3,77.7,224,100,10],index = ["val 1","val 2","val 3","val 4","val 5"], name="Xamir's Serie")
xamir_serie

val 1     33.3
val 2     77.7
val 3    224.0
val 4    100.0
val 5     10.0
Name: Xamir's Serie, dtype: float64

## Time Index

In [145]:
time_index = pd.date_range('2017-01-01',periods = len(s),freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Price List, dtype: float64


In [146]:
# Xamir
xamir_time_index = pd.date_range('2021-10-16',periods = len(xamir_serie),freq = 'D')
print(xamir_time_index)
xamir_serie.index = xamir_time_index
print(xamir_serie)

DatetimeIndex(['2021-10-16', '2021-10-17', '2021-10-18', '2021-10-19',
               '2021-10-20'],
              dtype='datetime64[ns]', freq='D')
2021-10-16     33.3
2021-10-17     77.7
2021-10-18    224.0
2021-10-19    100.0
2021-10-20     10.0
Freq: D, Name: Xamir's Serie, dtype: float64


## Accessing, iloc and loc 
Series are usually accessed using the iloc[] and loc[] methods. iloc[] is used to access elements by integer index, and loc[] is used to access the index of the series.

iloc[] is necessary when the index of a series are integers, take our previous defined series as example:



In [147]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Price List, dtype: float64
142.62


In [148]:
# Xamir
xamir_serie.index = [7,3,5,2,1]
print(xamir_serie)
xamir_serie[1] #using key

7     33.3
3     77.7
5    224.0
2    100.0
1     10.0
Name: Xamir's Serie, dtype: float64


10.0

In [149]:
print(s.iloc[1])

145.83


In [150]:
# Xamir
print(xamir_serie.iloc[1]) # accessing the position

77.7


In [151]:
s.index = time_index
print(s['2017-01-03'])

143.68


In [152]:
# Xamir
xamir_serie.index = xamir_time_index
xamir_serie['2021-10-16']

33.3

In [153]:
print(s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Price List, dtype: float64


In [154]:
# Xamir
print(xamir_serie['2021-10-16':'2021-10-18'])

2021-10-16     33.3
2021-10-17     77.7
2021-10-18    224.0
Freq: D, Name: Xamir's Serie, dtype: float64


## Index data with conditions int the square brackets
Series[] provides us a very flexible way to index data. We can add any condition in the square brackets:
As demonstrated, we can use logical operators like & (and), | (or) and ~ (not) to group multiple conditions.

In [155]:

print(s[s < np.mean(s)] )
print([(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Price List, dtype: float64
[2017-01-01    False
2017-01-02    False
2017-01-03    False
2017-01-04     True
2017-01-05    False
2017-01-06    False
Freq: D, Name: Apple Price List, dtype: bool]


In [156]:
# Xamir
print("Xamir's Serie")
print(xamir_serie)
print("Mean of the serie : " +str(np.mean(xamir_serie)))
print("Items in xamir's serie < mean of the serie")
print(xamir_serie[xamir_serie < np.mean(xamir_serie)] )

Xamir's Serie
2021-10-16     33.3
2021-10-17     77.7
2021-10-18    224.0
2021-10-19    100.0
2021-10-20     10.0
Freq: D, Name: Xamir's Serie, dtype: float64
Mean of the serie : 89.0
Items in xamir's serie < mean of the serie
2021-10-16    33.3
2021-10-17    77.7
2021-10-20    10.0
Name: Xamir's Serie, dtype: float64


In [157]:
# Xamir 

print("Items in serie > mean of the serie")
print(xamir_serie[xamir_serie > np.mean(xamir_serie)])
print("Items in serie < ( mean of the serie + standard deviation of the serie)")
print(xamir_serie[xamir_serie < np.mean(xamir_serie) + 1.64*np.std(xamir_serie)])
print("Items in serie > mean of the serie AND Items in serie < ( mean of the serie + standard deviation of the serie)")
print(xamir_serie[(xamir_serie > np.mean(xamir_serie)) & (xamir_serie < np.mean(xamir_serie) + 1.64*np.std(xamir_serie))])


Items in serie > mean of the serie
2021-10-18    224.0
2021-10-19    100.0
Freq: D, Name: Xamir's Serie, dtype: float64
Items in serie < ( mean of the serie + standard deviation of the serie)
2021-10-16     33.3
2021-10-17     77.7
2021-10-19    100.0
2021-10-20     10.0
Name: Xamir's Serie, dtype: float64
Items in serie > mean of the serie AND Items in serie < ( mean of the serie + standard deviation of the serie)
2021-10-19    100.0
Freq: D, Name: Xamir's Serie, dtype: float64
